import { MigrationInterface, QueryRunner } from "typeorm";

export class Auto1761094912790 implements MigrationInterface {
    name = 'Auto1761094912790'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "historial_medico" DROP CONSTRAINT "historial_medico_mascota_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "puntos_recorrido" DROP CONSTRAINT "puntos_recorrido_recorrido_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "realizado_por" DROP CONSTRAINT "realizado_por_mascota_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "realizado_por" DROP CONSTRAINT "realizado_por_recorrido_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "recorrido" DROP CONSTRAINT "recorrido_usuario_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "recorrido" DROP CONSTRAINT "recorrido_mascota_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "comentario" DROP CONSTRAINT "comentario_publicacion_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "comentario" DROP CONSTRAINT "comentario_usuario_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "publicacion" DROP CONSTRAINT "publicacion_usuario_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "publicacion" DROP CONSTRAINT "publicacion_mascota_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "mascota" DROP CONSTRAINT "mascota_usuario_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "resena" DROP CONSTRAINT "resena_id_punto_interes_fkey"`);
        await queryRunner.query(`ALTER TABLE "resena" DROP CONSTRAINT "resena_id_usuario_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_hist_med_mascota"`);
        await queryRunner.query(`DROP INDEX "public"."idx_puntos_recorrido"`);
        await queryRunner.query(`DROP INDEX "public"."idx_recorrido_usuario"`);
        await queryRunner.query(`DROP INDEX "public"."idx_recorrido_mascota"`);
        await queryRunner.query(`DROP INDEX "public"."idx_com_pub"`);
        await queryRunner.query(`DROP INDEX "public"."idx_com_usuario"`);
        await queryRunner.query(`DROP INDEX "public"."idx_resena_poi"`);
        await queryRunner.query(`DROP INDEX "public"."idx_resena_usuario"`);
        await queryRunner.query(`ALTER TABLE "historial_medico" RENAME COLUMN "mascota_id" TO "mascotaMascotaId"`);
        await queryRunner.query(`ALTER TABLE "puntos_recorrido" RENAME COLUMN "recorrido_id" TO "recorridoId"`);
        await queryRunner.query(`ALTER TABLE "realizado_por" DROP COLUMN "mascota_id"`);
        await queryRunner.query(`ALTER TABLE "realizado_por" DROP COLUMN "recorrido_id"`);
        await queryRunner.query(`ALTER TABLE "recorrido" DROP COLUMN "usuario_id"`);
        await queryRunner.query(`ALTER TABLE "recorrido" DROP COLUMN "mascota_id"`);
        await queryRunner.query(`ALTER TABLE "comentario" DROP COLUMN "publicacion_id"`);
        await queryRunner.query(`ALTER TABLE "comentario" DROP COLUMN "usuario_id"`);
        await queryRunner.query(`ALTER TABLE "publicacion" DROP COLUMN "contador_comentarios"`);
        await queryRunner.query(`ALTER TABLE "publicacion" DROP COLUMN "contador_compartidos"`);
        await queryRunner.query(`ALTER TABLE "resena" DROP COLUMN "id_punto_interes"`);
        await queryRunner.query(`ALTER TABLE "resena" DROP COLUMN "id_usuario"`);
        await queryRunner.query(`ALTER TABLE "realizado_por" ADD "mascotaMascotaId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "realizado_por" ADD "recorridoId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recorrido" ADD "usuarioUsuarioId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recorrido" ADD "mascotaMascotaId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "comentario" ADD "publicacionId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "comentario" ADD "usuarioUsuarioId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "punto_de_interes" ADD "suma_valoraciones" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "punto_de_interes" ADD "cantidad_resenas" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "resena" ADD "puntoInteresId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resena" ADD "usuarioUsuarioId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP CONSTRAINT "uk_usuario_email"`);
        await queryRunner.query(`CREATE INDEX "idx_hist_med_mascota" ON "historial_medico" ("mascotaMascotaId") `);
        await queryRunner.query(`CREATE INDEX "idx_puntos_recorrido" ON "puntos_recorrido" ("recorridoId") `);
        await queryRunner.query(`CREATE INDEX "idx_recorrido_mascota" ON "recorrido" ("mascotaMascotaId") `);
        await queryRunner.query(`CREATE INDEX "idx_recorrido_usuario" ON "recorrido" ("usuarioUsuarioId") `);
        await queryRunner.query(`CREATE INDEX "idx_com_usuario" ON "comentario" ("usuarioUsuarioId") `);
        await queryRunner.query(`CREATE INDEX "idx_com_pub" ON "comentario" ("publicacionId") `);
        await queryRunner.query(`CREATE INDEX "idx_resena_usuario" ON "resena" ("usuarioUsuarioId") `);
        await queryRunner.query(`CREATE INDEX "idx_resena_poi" ON "resena" ("puntoInteresId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2863682842e688ca198eb25c12" ON "usuario" ("email") `);
        await queryRunner.query(`ALTER TABLE "historial_medico" ADD CONSTRAINT "FK_8baefea3c26689e7e7a690650a4" FOREIGN KEY ("mascotaMascotaId") REFERENCES "mascota"("mascota_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "puntos_recorrido" ADD CONSTRAINT "FK_5c72dca7bae96d558cca476a88f" FOREIGN KEY ("recorridoId") REFERENCES "recorrido"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "realizado_por" ADD CONSTRAINT "FK_a5715c5e31ad3faa04994455ef0" FOREIGN KEY ("mascotaMascotaId") REFERENCES "mascota"("mascota_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "realizado_por" ADD CONSTRAINT "FK_d2ae088ec13a41a2b971a74cce9" FOREIGN KEY ("recorridoId") REFERENCES "recorrido"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recorrido" ADD CONSTRAINT "FK_8cc6d1eee8e7a878af3548199f8" FOREIGN KEY ("usuarioUsuarioId") REFERENCES "usuario"("usuario_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recorrido" ADD CONSTRAINT "FK_41d1c5844f85ec1f88e9b1d76ce" FOREIGN KEY ("mascotaMascotaId") REFERENCES "mascota"("mascota_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comentario" ADD CONSTRAINT "FK_71f95d912cda6a3108075fc41ef" FOREIGN KEY ("publicacionId") REFERENCES "publicacion"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comentario" ADD CONSTRAINT "FK_424c2a1af9446d19d8b5f43121a" FOREIGN KEY ("usuarioUsuarioId") REFERENCES "usuario"("usuario_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "publicacion" ADD CONSTRAINT "FK_4dab3e7102c5e3fc8cfaaffb716" FOREIGN KEY ("usuario_id") REFERENCES "usuario"("usuario_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "publicacion" ADD CONSTRAINT "FK_44e6cceda4eb93984687c6990e7" FOREIGN KEY ("mascota_id") REFERENCES "mascota"("mascota_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mascota" ADD CONSTRAINT "FK_74d5fbc5f78c7d47988f7a9d5d9" FOREIGN KEY ("usuario_id") REFERENCES "usuario"("usuario_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resena" ADD CONSTRAINT "FK_da171027e97039357f9157eb781" FOREIGN KEY ("puntoInteresId") REFERENCES "punto_de_interes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resena" ADD CONSTRAINT "FK_7b0ec3fe1226f5fbcfe0ad5ab6a" FOREIGN KEY ("usuarioUsuarioId") REFERENCES "usuario"("usuario_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "resena" DROP CONSTRAINT "FK_7b0ec3fe1226f5fbcfe0ad5ab6a"`);
        await queryRunner.query(`ALTER TABLE "resena" DROP CONSTRAINT "FK_da171027e97039357f9157eb781"`);
        await queryRunner.query(`ALTER TABLE "mascota" DROP CONSTRAINT "FK_74d5fbc5f78c7d47988f7a9d5d9"`);
        await queryRunner.query(`ALTER TABLE "publicacion" DROP CONSTRAINT "FK_44e6cceda4eb93984687c6990e7"`);
        await queryRunner.query(`ALTER TABLE "publicacion" DROP CONSTRAINT "FK_4dab3e7102c5e3fc8cfaaffb716"`);
        await queryRunner.query(`ALTER TABLE "comentario" DROP CONSTRAINT "FK_424c2a1af9446d19d8b5f43121a"`);
        await queryRunner.query(`ALTER TABLE "comentario" DROP CONSTRAINT "FK_71f95d912cda6a3108075fc41ef"`);
        await queryRunner.query(`ALTER TABLE "recorrido" DROP CONSTRAINT "FK_41d1c5844f85ec1f88e9b1d76ce"`);
        await queryRunner.query(`ALTER TABLE "recorrido" DROP CONSTRAINT "FK_8cc6d1eee8e7a878af3548199f8"`);
        await queryRunner.query(`ALTER TABLE "realizado_por" DROP CONSTRAINT "FK_d2ae088ec13a41a2b971a74cce9"`);
        await queryRunner.query(`ALTER TABLE "realizado_por" DROP CONSTRAINT "FK_a5715c5e31ad3faa04994455ef0"`);
        await queryRunner.query(`ALTER TABLE "puntos_recorrido" DROP CONSTRAINT "FK_5c72dca7bae96d558cca476a88f"`);
        await queryRunner.query(`ALTER TABLE "historial_medico" DROP CONSTRAINT "FK_8baefea3c26689e7e7a690650a4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2863682842e688ca198eb25c12"`);
        await queryRunner.query(`DROP INDEX "public"."idx_resena_poi"`);
        await queryRunner.query(`DROP INDEX "public"."idx_resena_usuario"`);
        await queryRunner.query(`DROP INDEX "public"."idx_com_pub"`);
        await queryRunner.query(`DROP INDEX "public"."idx_com_usuario"`);
        await queryRunner.query(`DROP INDEX "public"."idx_recorrido_usuario"`);
        await queryRunner.query(`DROP INDEX "public"."idx_recorrido_mascota"`);
        await queryRunner.query(`DROP INDEX "public"."idx_puntos_recorrido"`);
        await queryRunner.query(`DROP INDEX "public"."idx_hist_med_mascota"`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD CONSTRAINT "uk_usuario_email" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "resena" DROP COLUMN "usuarioUsuarioId"`);
        await queryRunner.query(`ALTER TABLE "resena" DROP COLUMN "puntoInteresId"`);
        await queryRunner.query(`ALTER TABLE "punto_de_interes" DROP COLUMN "cantidad_resenas"`);
        await queryRunner.query(`ALTER TABLE "punto_de_interes" DROP COLUMN "suma_valoraciones"`);
        await queryRunner.query(`ALTER TABLE "comentario" DROP COLUMN "usuarioUsuarioId"`);
        await queryRunner.query(`ALTER TABLE "comentario" DROP COLUMN "publicacionId"`);
        await queryRunner.query(`ALTER TABLE "recorrido" DROP COLUMN "mascotaMascotaId"`);
        await queryRunner.query(`ALTER TABLE "recorrido" DROP COLUMN "usuarioUsuarioId"`);
        await queryRunner.query(`ALTER TABLE "realizado_por" DROP COLUMN "recorridoId"`);
        await queryRunner.query(`ALTER TABLE "realizado_por" DROP COLUMN "mascotaMascotaId"`);
        await queryRunner.query(`ALTER TABLE "resena" ADD "id_usuario" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resena" ADD "id_punto_interes" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "publicacion" ADD "contador_compartidos" integer`);
        await queryRunner.query(`ALTER TABLE "publicacion" ADD "contador_comentarios" integer`);
        await queryRunner.query(`ALTER TABLE "comentario" ADD "usuario_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "comentario" ADD "publicacion_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recorrido" ADD "mascota_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recorrido" ADD "usuario_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "realizado_por" ADD "recorrido_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "realizado_por" ADD "mascota_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "puntos_recorrido" RENAME COLUMN "recorridoId" TO "recorrido_id"`);
        await queryRunner.query(`ALTER TABLE "historial_medico" RENAME COLUMN "mascotaMascotaId" TO "mascota_id"`);
        await queryRunner.query(`CREATE INDEX "idx_resena_usuario" ON "resena" ("id_usuario") `);
        await queryRunner.query(`CREATE INDEX "idx_resena_poi" ON "resena" ("id_punto_interes") `);
        await queryRunner.query(`CREATE INDEX "idx_com_usuario" ON "comentario" ("usuario_id") `);
        await queryRunner.query(`CREATE INDEX "idx_com_pub" ON "comentario" ("publicacion_id") `);
        await queryRunner.query(`CREATE INDEX "idx_recorrido_mascota" ON "recorrido" ("mascota_id") `);
        await queryRunner.query(`CREATE INDEX "idx_recorrido_usuario" ON "recorrido" ("usuario_id") `);
        await queryRunner.query(`CREATE INDEX "idx_puntos_recorrido" ON "puntos_recorrido" ("recorrido_id") `);
        await queryRunner.query(`CREATE INDEX "idx_hist_med_mascota" ON "historial_medico" ("mascota_id") `);
        await queryRunner.query(`ALTER TABLE "resena" ADD CONSTRAINT "resena_id_usuario_fkey" FOREIGN KEY ("id_usuario") REFERENCES "usuario"("usuario_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resena" ADD CONSTRAINT "resena_id_punto_interes_fkey" FOREIGN KEY ("id_punto_interes") REFERENCES "punto_de_interes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mascota" ADD CONSTRAINT "mascota_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "usuario"("usuario_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "publicacion" ADD CONSTRAINT "publicacion_mascota_id_fkey" FOREIGN KEY ("mascota_id") REFERENCES "mascota"("mascota_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "publicacion" ADD CONSTRAINT "publicacion_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "usuario"("usuario_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comentario" ADD CONSTRAINT "comentario_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "usuario"("usuario_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comentario" ADD CONSTRAINT "comentario_publicacion_id_fkey" FOREIGN KEY ("publicacion_id") REFERENCES "publicacion"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recorrido" ADD CONSTRAINT "recorrido_mascota_id_fkey" FOREIGN KEY ("mascota_id") REFERENCES "mascota"("mascota_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recorrido" ADD CONSTRAINT "recorrido_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "usuario"("usuario_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "realizado_por" ADD CONSTRAINT "realizado_por_recorrido_id_fkey" FOREIGN KEY ("recorrido_id") REFERENCES "recorrido"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "realizado_por" ADD CONSTRAINT "realizado_por_mascota_id_fkey" FOREIGN KEY ("mascota_id") REFERENCES "mascota"("mascota_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "puntos_recorrido" ADD CONSTRAINT "puntos_recorrido_recorrido_id_fkey" FOREIGN KEY ("recorrido_id") REFERENCES "recorrido"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "historial_medico" ADD CONSTRAINT "historial_medico_mascota_id_fkey" FOREIGN KEY ("mascota_id") REFERENCES "mascota"("mascota_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
